# Generated by Django 4.0.3 on 2022-04-10 23:58

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_userextension_fecha_creacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('subtitulo', models.CharField(max_length=100)),
                ('cuerpo', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('autor', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagen')),
            ],
        ),
        migrations.RemoveField(
            model_name='userextension',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='userextension',
            name='tarjeta_presentacion',
        ),
    ]
